//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("MyLegoCarService")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("MyLegoCarService")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="MyLegoCarService.Y2010.M09, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6111" +
    "f4f52f855ee1")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.AllowPartiallyTrustedCallersAttribute()]

namespace Dss.Transforms.TransformMyLegoCarService {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::MyLegoCarService.Proxy.MyLegoCarServiceState), new global::Microsoft.Dss.Core.Attributes.Transform(MyLegoCarService_Proxy_MyLegoCarServiceState_TO_MyLegoCarService_MyLegoCarServiceState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::MyLegoCarService.MyLegoCarServiceState), new global::Microsoft.Dss.Core.Attributes.Transform(MyLegoCarService_MyLegoCarServiceState_TO_MyLegoCarService_Proxy_MyLegoCarServiceState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::MyLegoCarService.Proxy.TimerTickRequest), new global::Microsoft.Dss.Core.Attributes.Transform(MyLegoCarService_Proxy_TimerTickRequest_TO_MyLegoCarService_TimerTickRequest));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::MyLegoCarService.TimerTickRequest), new global::Microsoft.Dss.Core.Attributes.Transform(MyLegoCarService_TimerTickRequest_TO_MyLegoCarService_Proxy_TimerTickRequest));
        }
        
        private static global::MyLegoCarService.Proxy.MyLegoCarServiceState _cachedInstance0 = new global::MyLegoCarService.Proxy.MyLegoCarServiceState();
        
        private static global::MyLegoCarService.MyLegoCarServiceState _cachedInstance = new global::MyLegoCarService.MyLegoCarServiceState();
        
        public static object MyLegoCarService_Proxy_MyLegoCarServiceState_TO_MyLegoCarService_MyLegoCarServiceState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object MyLegoCarService_MyLegoCarServiceState_TO_MyLegoCarService_Proxy_MyLegoCarServiceState(object transformFrom) {
            return _cachedInstance0;
        }
        
        private static global::MyLegoCarService.Proxy.TimerTickRequest _cachedInstance2 = new global::MyLegoCarService.Proxy.TimerTickRequest();
        
        private static global::MyLegoCarService.TimerTickRequest _cachedInstance1 = new global::MyLegoCarService.TimerTickRequest();
        
        public static object MyLegoCarService_Proxy_TimerTickRequest_TO_MyLegoCarService_TimerTickRequest(object transformFrom) {
            return _cachedInstance1;
        }
        
        public static object MyLegoCarService_TimerTickRequest_TO_MyLegoCarService_Proxy_TimerTickRequest(object transformFrom) {
            return _cachedInstance2;
        }
    }
}
